// <auto-generated />
using System;
using EntityFrameworkCore.Jet.Metadata;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using dodoEF.MyEF.Entities;

#nullable disable

namespace dodoEF.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260530203800_add_full_Migration")]
    partial class add_full_Migration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Jet:ValueGenerationStrategy", JetValueGenerationStrategy.IdentityColumn)
                .HasAnnotation("ProductVersion", "10.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("OderTovar", b =>
                {
                    b.Property<int>("odersId")
                        .HasColumnType("integer");

                    b.Property<int>("tovarsId")
                        .HasColumnType("integer");

                    b.HasKey("odersId", "tovarsId");

                    b.HasIndex("tovarsId");

                    b.ToTable("OderTovar");
                });

            modelBuilder.Entity("dodoEF.MyEF.Entities.Categori", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Jet:ValueGenerationStrategy", JetValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Tatle")
                        .IsRequired()
                        .HasColumnType("longchar");

                    b.HasKey("Id");

                    b.ToTable("Categori");
                });

            modelBuilder.Entity("dodoEF.MyEF.Entities.Client", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Jet:ValueGenerationStrategy", JetValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Adress_C")
                        .IsRequired()
                        .HasColumnType("longchar");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("longchar");

                    b.Property<string>("Login")
                        .IsRequired()
                        .HasColumnType("longchar");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("longchar");

                    b.Property<int>("Telefon")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("Client");
                });

            modelBuilder.Entity("dodoEF.MyEF.Entities.Evelobilitile", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Jet:ValueGenerationStrategy", JetValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Enum_Evel")
                        .IsRequired()
                        .HasColumnType("longchar");

                    b.Property<string>("Enum_Oder")
                        .IsRequired()
                        .HasColumnType("longchar");

                    b.Property<string>("FullName_P")
                        .IsRequired()
                        .HasColumnType("longchar");

                    b.Property<int>("Pizziria")
                        .HasColumnType("integer");

                    b.Property<string>("Procent")
                        .IsRequired()
                        .HasColumnType("longchar");

                    b.Property<int>("Reit_K_D")
                        .HasColumnType("integer");

                    b.Property<int>("personalId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("personalId");

                    b.ToTable("Evelobilitile");
                });

            modelBuilder.Entity("dodoEF.MyEF.Entities.Ingr", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Jet:ValueGenerationStrategy", JetValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Cost")
                        .HasColumnType("integer");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("longchar");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer");

                    b.Property<DateTime>("date")
                        .HasColumnType("datetime");

                    b.Property<int>("tovarid")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("tovarid");

                    b.ToTable("Ingr");
                });

            modelBuilder.Entity("dodoEF.MyEF.Entities.Oder", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Jet:ValueGenerationStrategy", JetValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Adress_d")
                        .IsRequired()
                        .HasColumnType("longchar");

                    b.Property<int?>("PersonalId")
                        .HasColumnType("integer");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("longchar");

                    b.Property<int>("Summa")
                        .HasColumnType("integer");

                    b.Property<int>("clientId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("date")
                        .HasColumnType("datetime");

                    b.Property<int>("plategid")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("PersonalId");

                    b.HasIndex("clientId");

                    b.HasIndex("plategid");

                    b.ToTable("Oder");
                });

            modelBuilder.Entity("dodoEF.MyEF.Entities.Personal", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Jet:ValueGenerationStrategy", JetValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("longchar");

                    b.Property<string>("Login")
                        .IsRequired()
                        .HasColumnType("longchar");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("longchar");

                    b.Property<int>("Stage")
                        .HasColumnType("integer");

                    b.Property<int>("categoriId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("categoriId");

                    b.ToTable("DbPersonal");
                });

            modelBuilder.Entity("dodoEF.MyEF.Entities.Plateg", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Jet:ValueGenerationStrategy", JetValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Sposob_PL")
                        .IsRequired()
                        .HasColumnType("longchar");

                    b.Property<string>("Status_PL")
                        .IsRequired()
                        .HasColumnType("longchar");

                    b.HasKey("Id");

                    b.ToTable("Plateg");
                });

            modelBuilder.Entity("dodoEF.MyEF.Entities.Tovar", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Jet:ValueGenerationStrategy", JetValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Callory")
                        .HasColumnType("integer");

                    b.Property<string>("Catifori_T")
                        .IsRequired()
                        .HasColumnType("longchar");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("longchar");

                    b.Property<int>("Price")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("Tovar");
                });

            modelBuilder.Entity("OderTovar", b =>
                {
                    b.HasOne("dodoEF.MyEF.Entities.Oder", null)
                        .WithMany()
                        .HasForeignKey("odersId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("dodoEF.MyEF.Entities.Tovar", null)
                        .WithMany()
                        .HasForeignKey("tovarsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("dodoEF.MyEF.Entities.Evelobilitile", b =>
                {
                    b.HasOne("dodoEF.MyEF.Entities.Personal", "Personal")
                        .WithMany("evelobilitiles")
                        .HasForeignKey("personalId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Personal");
                });

            modelBuilder.Entity("dodoEF.MyEF.Entities.Ingr", b =>
                {
                    b.HasOne("dodoEF.MyEF.Entities.Tovar", "tovars")
                        .WithMany("ingrs")
                        .HasForeignKey("tovarid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("tovars");
                });

            modelBuilder.Entity("dodoEF.MyEF.Entities.Oder", b =>
                {
                    b.HasOne("dodoEF.MyEF.Entities.Personal", null)
                        .WithMany("oders")
                        .HasForeignKey("PersonalId");

                    b.HasOne("dodoEF.MyEF.Entities.Client", "client")
                        .WithMany("oders")
                        .HasForeignKey("clientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("dodoEF.MyEF.Entities.Plateg", "plategs")
                        .WithMany("oders")
                        .HasForeignKey("plategid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("client");

                    b.Navigation("plategs");
                });

            modelBuilder.Entity("dodoEF.MyEF.Entities.Personal", b =>
                {
                    b.HasOne("dodoEF.MyEF.Entities.Categori", "categori")
                        .WithMany()
                        .HasForeignKey("categoriId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("categori");
                });

            modelBuilder.Entity("dodoEF.MyEF.Entities.Client", b =>
                {
                    b.Navigation("oders");
                });

            modelBuilder.Entity("dodoEF.MyEF.Entities.Personal", b =>
                {
                    b.Navigation("evelobilitiles");

                    b.Navigation("oders");
                });

            modelBuilder.Entity("dodoEF.MyEF.Entities.Plateg", b =>
                {
                    b.Navigation("oders");
                });

            modelBuilder.Entity("dodoEF.MyEF.Entities.Tovar", b =>
                {
                    b.Navigation("ingrs");
                });
#pragma warning restore 612, 618
        }
    }
}
