// <auto-generated />
using System;
using EntityFrameworkCore.Jet.Metadata;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using dodoEF.MyEF.Entities;

#nullable disable

namespace dodoEF.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260606110737_cdacha_kur_06.06.2026")]
    partial class cdacha_kur_06062026
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Jet:ValueGenerationStrategy", JetValueGenerationStrategy.IdentityColumn)
                .HasAnnotation("ProductVersion", "8.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("dodoEF.MyEF.Entities.Categori", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Jet:ValueGenerationStrategy", JetValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Tatle")
                        .IsRequired()
                        .HasColumnType("longchar");

                    b.HasKey("Id");

                    b.ToTable("Categori");
                });

            modelBuilder.Entity("dodoEF.MyEF.Entities.Client", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Jet:ValueGenerationStrategy", JetValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Adress_C")
                        .IsRequired()
                        .HasColumnType("longchar");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("longchar");

                    b.Property<string>("Login")
                        .IsRequired()
                        .HasColumnType("longchar");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("longchar");

                    b.Property<int>("Telefon")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("Client");
                });

            modelBuilder.Entity("dodoEF.MyEF.Entities.Evelobilitile", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Jet:ValueGenerationStrategy", JetValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Enum_Evel")
                        .IsRequired()
                        .HasColumnType("longchar");

                    b.Property<string>("Enum_Oder")
                        .IsRequired()
                        .HasColumnType("longchar");

                    b.Property<string>("FullName_P")
                        .IsRequired()
                        .HasColumnType("longchar");

                    b.Property<int>("Pizziria")
                        .HasColumnType("integer");

                    b.Property<string>("Procent")
                        .IsRequired()
                        .HasColumnType("longchar");

                    b.Property<int>("Reit_K_D")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("Evelobilitile");
                });

            modelBuilder.Entity("dodoEF.MyEF.Entities.Ingr", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Jet:ValueGenerationStrategy", JetValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Cost")
                        .HasColumnType("integer");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("longchar");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer");

                    b.Property<DateTime>("date")
                        .HasColumnType("datetime");

                    b.HasKey("Id");

                    b.ToTable("Ingr");
                });

            modelBuilder.Entity("dodoEF.MyEF.Entities.Oder", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Jet:ValueGenerationStrategy", JetValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Adress_d")
                        .IsRequired()
                        .HasColumnType("longchar");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("longchar");

                    b.Property<int>("Summa")
                        .HasColumnType("integer");

                    b.Property<int>("clientId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("date")
                        .HasColumnType("datetime");

                    b.Property<int?>("personalId")
                        .HasColumnType("integer");

                    b.Property<int>("plategid")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("clientId");

                    b.HasIndex("personalId");

                    b.HasIndex("plategid")
                        .IsUnique();

                    b.ToTable("Oder");
                });

            modelBuilder.Entity("dodoEF.MyEF.Entities.OderTovar", b =>
                {
                    b.Property<int>("OderId")
                        .HasColumnType("integer");

                    b.Property<int>("TovarId")
                        .HasColumnType("integer");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer");

                    b.HasKey("OderId", "TovarId");

                    b.HasIndex("TovarId");

                    b.ToTable("OderTovars");
                });

            modelBuilder.Entity("dodoEF.MyEF.Entities.Personal", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Jet:ValueGenerationStrategy", JetValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("longchar");

                    b.Property<string>("Login")
                        .IsRequired()
                        .HasColumnType("longchar");

                    b.Property<int>("Num_Car")
                        .HasColumnType("integer");

                    b.Property<int>("Num_VY")
                        .HasColumnType("integer");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("longchar");

                    b.Property<int>("Stage")
                        .HasColumnType("integer");

                    b.Property<int>("categoriId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("categoriId");

                    b.ToTable("DbPersonal");
                });

            modelBuilder.Entity("dodoEF.MyEF.Entities.PersonalEvelobilitile", b =>
                {
                    b.Property<int>("PersonalId")
                        .HasColumnType("integer");

                    b.Property<int>("EvelobilitileId")
                        .HasColumnType("integer");

                    b.HasKey("PersonalId", "EvelobilitileId");

                    b.HasIndex("EvelobilitileId");

                    b.ToTable("PersonalEvelobilitile");
                });

            modelBuilder.Entity("dodoEF.MyEF.Entities.Plateg", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Jet:ValueGenerationStrategy", JetValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Sposob_PL")
                        .IsRequired()
                        .HasColumnType("longchar");

                    b.Property<string>("Status_PL")
                        .IsRequired()
                        .HasColumnType("longchar");

                    b.HasKey("Id");

                    b.ToTable("Plateg");
                });

            modelBuilder.Entity("dodoEF.MyEF.Entities.Tovar", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Jet:ValueGenerationStrategy", JetValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Callory")
                        .HasColumnType("integer");

                    b.Property<string>("Catifori_T")
                        .IsRequired()
                        .HasColumnType("longchar");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("longchar");

                    b.Property<int>("Price")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("Tovar");
                });

            modelBuilder.Entity("dodoEF.MyEF.Entities.TovarIngr", b =>
                {
                    b.Property<int>("TovarId")
                        .HasColumnType("integer");

                    b.Property<int>("IngrId")
                        .HasColumnType("integer");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer");

                    b.HasKey("TovarId", "IngrId");

                    b.HasIndex("IngrId");

                    b.ToTable("TovarIngrs");
                });

            modelBuilder.Entity("dodoEF.MyEF.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Jet:ValueGenerationStrategy", JetValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("smallint");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("dodoEF.MyEF.Entities.Oder", b =>
                {
                    b.HasOne("dodoEF.MyEF.Entities.Client", "client")
                        .WithMany("oders")
                        .HasForeignKey("clientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("dodoEF.MyEF.Entities.Personal", "personal")
                        .WithMany("oders")
                        .HasForeignKey("personalId");

                    b.HasOne("dodoEF.MyEF.Entities.Plateg", "plategs")
                        .WithOne("Oder")
                        .HasForeignKey("dodoEF.MyEF.Entities.Oder", "plategid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("client");

                    b.Navigation("personal");

                    b.Navigation("plategs");
                });

            modelBuilder.Entity("dodoEF.MyEF.Entities.OderTovar", b =>
                {
                    b.HasOne("dodoEF.MyEF.Entities.Oder", "Oder")
                        .WithMany("OderTovars")
                        .HasForeignKey("OderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("dodoEF.MyEF.Entities.Tovar", "Tovar")
                        .WithMany("OderTovars")
                        .HasForeignKey("TovarId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Oder");

                    b.Navigation("Tovar");
                });

            modelBuilder.Entity("dodoEF.MyEF.Entities.Personal", b =>
                {
                    b.HasOne("dodoEF.MyEF.Entities.Categori", "categori")
                        .WithMany("Personals")
                        .HasForeignKey("categoriId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("categori");
                });

            modelBuilder.Entity("dodoEF.MyEF.Entities.PersonalEvelobilitile", b =>
                {
                    b.HasOne("dodoEF.MyEF.Entities.Evelobilitile", "Evelobilitile")
                        .WithMany("PersonalEvelobilitiles")
                        .HasForeignKey("EvelobilitileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("dodoEF.MyEF.Entities.Personal", "Personal")
                        .WithMany("PersonalEvelobilitiles")
                        .HasForeignKey("PersonalId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Evelobilitile");

                    b.Navigation("Personal");
                });

            modelBuilder.Entity("dodoEF.MyEF.Entities.TovarIngr", b =>
                {
                    b.HasOne("dodoEF.MyEF.Entities.Ingr", "Ingr")
                        .WithMany("TovarIngrs")
                        .HasForeignKey("IngrId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("dodoEF.MyEF.Entities.Tovar", "Tovar")
                        .WithMany("TovarIngrs")
                        .HasForeignKey("TovarId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Ingr");

                    b.Navigation("Tovar");
                });

            modelBuilder.Entity("dodoEF.MyEF.Entities.Categori", b =>
                {
                    b.Navigation("Personals");
                });

            modelBuilder.Entity("dodoEF.MyEF.Entities.Client", b =>
                {
                    b.Navigation("oders");
                });

            modelBuilder.Entity("dodoEF.MyEF.Entities.Evelobilitile", b =>
                {
                    b.Navigation("PersonalEvelobilitiles");
                });

            modelBuilder.Entity("dodoEF.MyEF.Entities.Ingr", b =>
                {
                    b.Navigation("TovarIngrs");
                });

            modelBuilder.Entity("dodoEF.MyEF.Entities.Oder", b =>
                {
                    b.Navigation("OderTovars");
                });

            modelBuilder.Entity("dodoEF.MyEF.Entities.Personal", b =>
                {
                    b.Navigation("PersonalEvelobilitiles");

                    b.Navigation("oders");
                });

            modelBuilder.Entity("dodoEF.MyEF.Entities.Plateg", b =>
                {
                    b.Navigation("Oder")
                        .IsRequired();
                });

            modelBuilder.Entity("dodoEF.MyEF.Entities.Tovar", b =>
                {
                    b.Navigation("OderTovars");

                    b.Navigation("TovarIngrs");
                });
#pragma warning restore 612, 618
        }
    }
}
